# Generated by Django 5.2.10 on 2026-02-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersession",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
