# Generated by Django 5.2.10 on 2026-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_app", "0002_ordersession_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
