# Generated by Django 6.0.1 on 2026-02-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_alter_restaurant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='restaurant_app.restaurant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='table',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='restaurant_app.hall'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('hall', 'table_number')},
        ),
    ]
