# Generated by Django 6.0.1 on 2026-02-05 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_hall_alter_table_unique_together_table_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant_app.hall'),
        ),
    ]
