# Generated by Django 6.0.1 on 2026-02-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_alter_table_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allow_half',
            field=models.BooleanField(default=False),
        ),
    ]
