# Generated by Django 6.0.1 on 2026-02-06 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_menuitem_allow_half'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurant_app.menuitem')),
            ],
            options={
                'db_table': 'menu_item_options',
                'ordering': ['name'],
            },
        ),
    ]
