# Generated by Django 6.0.1 on 2026-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_parcelorder_parcelbill_parcelorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='half_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
