# Generated by Django 6.0.1 on 2026-02-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_menuitem_half_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_logo_on_qr', models.BooleanField(default=True)),
                ('qr_custom_text', models.CharField(blank=True, max_length=120)),
                ('show_logo_on_bill', models.BooleanField(default=True)),
                ('show_address_on_bill', models.BooleanField(default=True)),
                ('show_phone_on_bill', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_settings', to='restaurant_app.restaurant')),
            ],
            options={
                'db_table': 'restaurant_print_settings',
            },
        ),
    ]
