# Generated by Django 6.0.1 on 2026-02-08 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0012_restaurantprintsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('qr', 'QR'), ('manager', 'Manager')], default='qr', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordersession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('bill_generated', 'Bill Generated'), ('paid', 'Paid')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordersession',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurant_app.table'),
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_groups', to='restaurant_app.restaurant')),
                ('tables', models.ManyToManyField(related_name='table_groups', to='restaurant_app.table')),
            ],
            options={
                'db_table': 'table_groups',
            },
        ),
        migrations.AddField(
            model_name='ordersession',
            name='table_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurant_app.tablegroup'),
        ),
    ]
