# Generated by Django 6.0.1 on 2026-02-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_bill_generated_by_bill_payment_mode_order_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_half',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='restaurant_app.menuitemoption'),
        ),
    ]
