# Generated by Django 6.0.1 on 2026-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0014_orderitem_is_half_orderitem_selected_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelbill',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], max_length=10, null=True),
        ),
    ]
