# Generated by Django 6.0.1 on 2026-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0015_parcelbill_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelorderitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='restaurant_app.menuitemoption'),
        ),
    ]
