# Generated by Django 6.0.1 on 2026-03-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0016_parcelorderitem_selected_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelorder',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='kitchen_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcelorder',
            name='kitchen_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
